# Generated by Django 5.1.2 on 2024-11-23 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="goal_type",
        ),
    ]
