# Generated by Django 5.1.2 on 2024-11-24 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0003_remove_program_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Joined"
            ),
        ),
    ]
