# Generated by Django 5.1.2 on 2024-11-26 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='payment_method',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogram',
            name='total_amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
