# Generated by Django 5.1.2 on 2024-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_userprogram_is_paid_userprogram_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogram',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
